# Generated by Django 5.0 on 2023-12-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='booking_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
